### ISSUE TITLE
Correction: Screen Wake Lock API doesn't require permission

### ISSUE THREAD

**Issue by tomayac** [HenrikJoreteg/joreteg.com#4]
This factual incorrectness unfortunately weakens the argument (of a besides that awesome post): https://github.com/HenrikJoreteg/joreteg.com/blob/master/posts/2020/06/project-fugu-a-new-hope.md#user-content-meanwhile-over-on-ie-ahem-i-mean-safari:~:text=which%20requires%20explicit%20permission.

**Comment by HenrikJoreteg** [comment]
😬 oops. Will fix

**Comment by HenrikJoreteg** [comment]
fixed! Thanks @tomayac
